# Generated by Django 4.2.8 on 2025-01-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('job', '0008_job_owner_alter_apply_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_city', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_country', to='cities_light.country'),
        ),
    ]
