# Generated by Django 4.2.8 on 2025-01-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_city_job_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
    ]
