# Generated by Django 4.2.8 on 2025-01-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_job_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
